#!/usr/bin/env python3
"""Generate a prioritized reverse backlog from the Ghidra ↔ repo mapping.

Input is `docs/reverse/generated/repo-function-map.csv` by default, generated by
`scripts/reverse/map_ghidra_to_repo.py`.
"""

from __future__ import annotations

import argparse
import csv
from collections import Counter, defaultdict
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

FINALISH = {"final", "debugged", "binary_matched"}
RUNTIME_TERMS = (
    "GAMEFLOW",
    "SETUP",
    "ROOMLOAD",
    "LOAD_LEV",
    "PSXMAIN",
    "PSXINPUT",
    "CD.",
    "SAVEGAME",
    "TITLE",
    "TITSEQ",
)
MODULE_WEIGHT = {
    "GAME": 350,
    "SPEC_PSXPC_N": 300,
    "SPEC_PSX": 120,
    "SPEC_PSXPC": 80,
    "SPEC_PC_N": 20,
}


@dataclass
class Row:
    final_psx_address: str
    beta_psx_address: str
    repo_function: str
    file: str
    line: int
    markers: set[str]
    comment: str
    mapping_status: str
    ghidra_entry: str
    ghidra_name: str
    body_size: int
    called_functions: str
    callers: str

    @property
    def module(self) -> str:
        return self.file.split("/", 1)[0] if "/" in self.file else "."

    @property
    def status(self) -> str:
        if "**" in self.markers:
            return "binary_matched"
        if "D" in self.markers:
            return "debugged"
        if "F" in self.markers:
            return "final"
        if self.repo_function and not self.repo_function.startswith(("sub_", "loc_", "FUN_")):
            return "decompiled"
        if self.mapping_status == "mapped" or self.ghidra_name:
            return "named"
        return "unknown"

    @property
    def nd(self) -> bool:
        return "ND" in self.markers

    @property
    def mapped(self) -> bool:
        return self.mapping_status == "mapped"

    @property
    def non_final(self) -> bool:
        return self.status not in FINALISH

    @property
    def runtime_focus(self) -> bool:
        haystack = f"{self.file} {self.repo_function}".upper()
        return any(term in haystack for term in RUNTIME_TERMS)

    @property
    def caller_count(self) -> int:
        return len([x for x in self.callers.split(";") if x])

    @property
    def callee_count(self) -> int:
        return len([x for x in self.called_functions.split(";") if x])


def parse_int(text: str | None) -> int:
    try:
        return int(text or "0")
    except ValueError:
        return 0


def parse_markers(text: str | None) -> set[str]:
    markers = set(filter(None, (part.strip() for part in (text or "").split(";"))))
    markers.discard("<")
    markers.discard(">")
    markers.discard("*")
    return markers


def read_rows(path: Path) -> list[Row]:
    with path.open(newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        rows = []
        for raw in reader:
            rows.append(
                Row(
                    final_psx_address=raw.get("final_psx_address", ""),
                    beta_psx_address=raw.get("beta_psx_address", ""),
                    repo_function=raw.get("repo_function", ""),
                    file=raw.get("file", ""),
                    line=parse_int(raw.get("line")),
                    markers=parse_markers(raw.get("markers")),
                    comment=raw.get("comment", ""),
                    mapping_status=raw.get("mapping_status", ""),
                    ghidra_entry=raw.get("ghidra_entry", ""),
                    ghidra_name=raw.get("ghidra_name", ""),
                    body_size=parse_int(raw.get("body_size")),
                    called_functions=raw.get("called_functions", ""),
                    callers=raw.get("callers", ""),
                )
            )
    return rows


def reason(row: Row) -> str:
    bits: list[str] = []
    if row.nd:
        bits.append("marqué ND")
    if row.runtime_focus:
        bits.append("chemin runtime/chargement/input")
    if row.mapped:
        bits.append("adresse Ghidra disponible")
    else:
        bits.append("repo-only: mapping à vérifier")
    if row.caller_count:
        bits.append(f"{row.caller_count} caller(s)")
    if row.callee_count:
        bits.append(f"{row.callee_count} callee(s)")
    if row.body_size:
        bits.append(f"body_size {row.body_size}")
    if row.status in {"decompiled", "named", "unknown"}:
        bits.append(f"statut {row.status}")
    return "; ".join(bits) or "fonction non finalisée"


def next_step(row: Row) -> str:
    if row.nd:
        return "Vérifier comportement, retirer ND seulement avec preuve/debug documenté."
    if not row.mapped:
        return "Vérifier l'adresse/commentaire puis mapper dans Ghidra avant de modifier le statut."
    if row.runtime_focus:
        return "Comparer MIPS/Ghidra avec le chemin runtime documenté, puis tester build si possible."
    return "Comparer Ghidra/MIPS, valider types/bit-fields, puis décider F ou D."


def score(row: Row) -> int:
    value = row.body_size + row.caller_count * 120 + row.callee_count * 35
    value += MODULE_WEIGHT.get(row.module, 0)
    if row.mapped:
        value += 500
    else:
        value -= 500
    if row.nd:
        value += 900
    if row.runtime_focus:
        value += 700
    if row.status == "decompiled":
        value += 250
    elif row.status == "named":
        value += 150
    elif row.status == "unknown":
        value -= 200
    if row.status in FINALISH and not row.nd:
        value -= 2000
    return value


def bucket(row: Row, value: int) -> str:
    if row.nd or (row.runtime_focus and row.mapped and row.non_final):
        return "P0"
    if row.mapped and row.non_final and value >= 1800:
        return "P1"
    return "P2"


def priority_rows(rows: list[Row]) -> list[dict[str, object]]:
    candidates = [row for row in rows if row.non_final or row.nd]
    output = []
    for row in candidates:
        value = score(row)
        output.append(
            {
                "bucket": bucket(row, value),
                "score": value,
                "final_psx_address": row.final_psx_address,
                "beta_psx_address": row.beta_psx_address,
                "repo_function": row.repo_function,
                "file": row.file,
                "line": row.line,
                "status": row.status,
                "markers": ";".join(sorted(row.markers)),
                "mapping_status": row.mapping_status,
                "ghidra_entry": row.ghidra_entry,
                "ghidra_name": row.ghidra_name,
                "body_size": row.body_size,
                "caller_count": row.caller_count,
                "callee_count": row.callee_count,
                "runtime_focus": "yes" if row.runtime_focus else "no",
                "nd": "yes" if row.nd else "no",
                "reason": reason(row),
                "next_step": next_step(row),
            }
        )
    output.sort(key=lambda item: (str(item["bucket"]), -int(item["score"]), str(item["file"]), int(item["line"])))
    for idx, item in enumerate(output, start=1):
        item["priority_rank"] = idx
    return output


def write_csv(path: Path, rows: list[dict[str, object]]) -> None:
    fields = [
        "priority_rank",
        "bucket",
        "score",
        "final_psx_address",
        "beta_psx_address",
        "repo_function",
        "file",
        "line",
        "status",
        "markers",
        "mapping_status",
        "ghidra_entry",
        "ghidra_name",
        "body_size",
        "caller_count",
        "callee_count",
        "runtime_focus",
        "nd",
        "reason",
        "next_step",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fields, lineterminator="\n")
        writer.writeheader()
        for row in rows:
            writer.writerow({field: row.get(field, "") for field in fields})


def md_row(item: dict[str, object]) -> list[str]:
    marker_text = item["markers"] or "none"
    return [
        f"- `#{item['priority_rank']}` `{item['final_psx_address']}` `{item['repo_function']}` — `{item['bucket']}` score `{item['score']}`",
        f"  - source: `{item['file']}:{item['line']}`; Ghidra: `{item['ghidra_entry'] or 'n/a'}` `{item['ghidra_name'] or 'n/a'}`",
        f"  - status: `{item['status']}`; markers: `{marker_text}`; ND: `{item['nd']}`; runtime: `{item['runtime_focus']}`",
        f"  - graph: callers `{item['caller_count']}`, callees `{item['callee_count']}`, body_size `{item['body_size']}`",
        f"  - why: {item['reason']}",
        f"  - next: {item['next_step']}",
    ]


def write_backlog(path: Path, source_csv: str, rows: list[dict[str, object]], all_rows: list[Row]) -> None:
    counts = Counter(str(item["bucket"]) for item in rows)
    status_counts = Counter(str(item["status"]) for item in rows)
    nd_count = sum(1 for item in rows if item["nd"] == "yes")
    mapped_count = sum(1 for item in rows if item["mapping_status"] == "mapped")
    hot_files: dict[str, list[dict[str, object]]] = defaultdict(list)
    for item in rows:
        hot_files[str(item["file"])].append(item)
    hot_file_rows = sorted(
        (
            {
                "file": file,
                "count": len(items),
                "mapped": sum(1 for item in items if item["mapping_status"] == "mapped"),
                "nd": sum(1 for item in items if item["nd"] == "yes"),
                "top_score": max(int(item["score"]) for item in items),
            }
            for file, items in hot_files.items()
        ),
        key=lambda item: (-item["count"], -item["mapped"], -item["top_score"], item["file"]),
    )

    lines: list[str] = [
        "# Backlog priorisée des fonctions reverse TOMB5",
        "",
        f"Generated: `{datetime.now(timezone.utc).isoformat()}`",
        f"Source: `{source_csv}`",
        f"CSV détaillé: `docs/reverse/generated/function-priority.csv`",
        "Story: `docs/stories/RE-004-priorisation-fonctions-non-finalisees.md`",
        "Status: Done",
        "",
        "## Progress tracker",
        "",
        "- [x] Définir une scoring rule reproductible.",
        "- [x] Consommer le mapping Ghidra/repo généré par RE-002.",
        "- [x] Classer les fonctions en lots actionnables.",
        "- [x] Pointer fichier source, ligne et adresse Ghidra quand disponible.",
        "- [x] Mettre en évidence les fonctions `(ND)`.",
        "",
        "## Scoring rule",
        "",
        "Le score est calculé par `scripts/reverse/function_priority.py`:",
        "",
        "```text",
        "score = body_size + callers*120 + callees*35",
        "      + module_weight",
        "      + 500 si mapped / -500 si repo-only",
        "      + 900 si ND",
        "      + 700 si runtime_focus",
        "      + status_weight",
        "```",
        "",
        "Pondérations module: `GAME=350`, `SPEC_PSXPC_N=300`, `SPEC_PSX=120`, `SPEC_PSXPC=80`, `SPEC_PC_N=20`.",
        "",
        "Pondérations statut: `decompiled=+250`, `named=+150`, `unknown=-200`. Les fonctions déjà final/debug/binary-matched ne restent candidates que si elles portent aussi `(ND)`, pour forcer une vérification de cohérence.",
        "",
        "`runtime_focus=yes` si le fichier ou le nom touche notamment `GAMEFLOW`, `SETUP`, `ROOMLOAD`, `LOAD_LEV`, `PSXMAIN`, `PSXINPUT`, `CD`, `SAVEGAME`, `TITLE` ou `TITSEQ`.",
        "",
        "Buckets:",
        "",
        "- `P0`: fonctions `(ND)` ou fonctions runtime non finalisées déjà mappées.",
        "- `P1`: fonctions non finalisées mappées avec score élevé.",
        "- `P2`: reste du backlog, surtout repo-only/unmapped ou faible impact immédiat.",
        "",
        "## Summary",
        "",
        f"- candidates total: `{len(rows)}` / repo rows `{len(all_rows)}`",
        f"- mapped candidates: `{mapped_count}`",
        f"- ND highlighted: `{nd_count}`",
        f"- P0: `{counts['P0']}`; P1: `{counts['P1']}`; P2: `{counts['P2']}`",
        "- statuses: " + "; ".join(f"`{key}` `{value}`" for key, value in sorted(status_counts.items())),
        "",
        "## Lot 1 — P0 runtime / ND à clarifier",
        "",
    ]
    for item in [row for row in rows if row["bucket"] == "P0"][:10]:
        lines.extend(md_row(item))
    lines.extend(["", "## Lot 2 — P1 grands hubs mappés", ""])
    for item in [row for row in rows if row["bucket"] == "P1"][:10]:
        lines.extend(md_row(item))
    lines.extend(["", "## Lot 3 — fichiers chauds à traiter par zones", ""])
    for item in hot_file_rows[:15]:
        lines.extend([
            f"- `{item['file']}`",
            f"  - candidates: `{item['count']}`; mapped: `{item['mapped']}`; ND: `{item['nd']}`; top score: `{item['top_score']}`",
        ])
    lines.extend(["", "## Lot 4 — P2 / pré-tri mapping", ""])
    for item in [row for row in rows if row["bucket"] == "P2"][:10]:
        lines.extend(md_row(item))
    lines.extend([
        "",
        "## Workflow recommandé par fonction",
        "",
        "1. Ouvrir l'adresse `ghidra_entry` si disponible; sinon vérifier d'abord le commentaire/adresse repo.",
        "2. Comparer la fonction avec `docs/reverse/conventions.md` et `docs/reverse/psx-exe-layout.md`.",
        "3. Vérifier types 32-bit, bit-fields et overlays avant toute modification de marqueur.",
        "4. Compiler ou documenter le blocage runtime/build selon le chemin touché.",
        "5. Ne marquer `(F)`, `(D)` ou `(**)` qu'en suivant la checklist de `docs/reverse/conventions.md`.",
        "",
        "## Acceptance criteria",
        "",
        "- [x] Une liste priorisée existe avec justification.",
        "- [x] Chaque entrée pointe vers un fichier source repo et une adresse Ghidra quand disponible.",
        "- [x] Les fonctions `(ND)` sont mises en évidence.",
        "- [x] Les lots sont assez petits pour être pris un par un.",
    ])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", default=".", help="TOMB5 repo root; default: current directory")
    parser.add_argument("--input", default="docs/reverse/generated/repo-function-map.csv", help="mapping CSV relative to repo root")
    parser.add_argument("--csv", default="docs/reverse/generated/function-priority.csv", help="priority CSV relative to repo root")
    parser.add_argument("--markdown", default="docs/reverse/backlog.md", help="backlog Markdown relative to repo root")
    args = parser.parse_args()

    repo = Path(args.repo).resolve()
    input_path = repo / args.input
    if not input_path.exists():
        raise SystemExit(f"Missing mapping CSV: {input_path}; run scripts/reverse/map_ghidra_to_repo.py first")
    rows = read_rows(input_path)
    priorities = priority_rows(rows)
    write_csv(repo / args.csv, priorities)
    write_backlog(repo / args.markdown, args.input, priorities, rows)
    print(f"wrote {len(priorities)} priorities to {args.csv}")
    print(f"wrote backlog to {args.markdown}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
