#!/usr/bin/env python3
"""Generate decompilation progress reports from the Ghidra ↔ repo mapping.

Input is `docs/reverse/generated/repo-function-map.csv` by default, generated by
`scripts/reverse/map_ghidra_to_repo.py`.
"""

from __future__ import annotations

import argparse
import csv
import json
from collections import Counter, defaultdict
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

STATUS_ORDER = ["unknown", "named", "decompiled", "final", "debugged", "binary_matched"]


@dataclass
class FunctionRow:
    final_psx_address: str
    beta_psx_address: str
    repo_function: str
    file: str
    line: int
    markers: set[str]
    comment: str
    mapping_status: str
    ghidra_name: str
    body_size: int
    called_functions: str
    callers: str

    @property
    def module(self) -> str:
        return self.file.split("/", 1)[0] if "/" in self.file else "."

    @property
    def status(self) -> str:
        # `(**)` is treated as strongest evidence when present: binary-matched.
        if "**" in self.markers:
            return "binary_matched"
        # `(D)` indicates debugged/diagnosed. It often coexists with `(F)`.
        if "D" in self.markers:
            return "debugged"
        if "F" in self.markers:
            return "final"
        if self.repo_function and not self.repo_function.startswith(("sub_", "loc_")):
            return "decompiled"
        if self.mapping_status == "mapped" or self.ghidra_name:
            return "named"
        return "unknown"

    @property
    def non_final(self) -> bool:
        return self.status not in {"final", "debugged", "binary_matched"}

    @property
    def nd(self) -> bool:
        return "ND" in self.markers

    @property
    def mapped(self) -> bool:
        return self.mapping_status == "mapped"


def parse_int(text: str) -> int:
    try:
        return int(text)
    except (TypeError, ValueError):
        return 0


def parse_markers(text: str) -> set[str]:
    markers = set(filter(None, (part.strip() for part in (text or "").split(";"))))
    # Ignore address decoration captured from `(<)` comments by the mapping parser.
    markers.discard("<")
    markers.discard(">")
    return markers


def read_rows(path: Path) -> list[FunctionRow]:
    with path.open(newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        rows = []
        for raw in reader:
            rows.append(
                FunctionRow(
                    final_psx_address=raw.get("final_psx_address", ""),
                    beta_psx_address=raw.get("beta_psx_address", ""),
                    repo_function=raw.get("repo_function", ""),
                    file=raw.get("file", ""),
                    line=parse_int(raw.get("line", "")),
                    markers=parse_markers(raw.get("markers", "")),
                    comment=raw.get("comment", ""),
                    mapping_status=raw.get("mapping_status", ""),
                    ghidra_name=raw.get("ghidra_name", ""),
                    body_size=parse_int(raw.get("body_size", "")),
                    called_functions=raw.get("called_functions", ""),
                    callers=raw.get("callers", ""),
                )
            )
    return rows


def pct(part: int, total: int) -> float:
    return round((part * 100.0 / total), 2) if total else 0.0


def summarize(rows: list[FunctionRow]) -> dict:
    def bucket(items: list[FunctionRow]) -> dict:
        status = Counter(row.status for row in items)
        total = len(items)
        finalish = status["final"] + status["debugged"] + status["binary_matched"]
        return {
            "total": total,
            "mapped": sum(1 for row in items if row.mapped),
            "repo_only": sum(1 for row in items if not row.mapped),
            "nd": sum(1 for row in items if row.nd),
            "statuses": {name: status[name] for name in STATUS_ORDER},
            "finalish": finalish,
            "finalish_percent": pct(finalish, total),
            "mapped_percent": pct(sum(1 for row in items if row.mapped), total),
        }

    modules: dict[str, list[FunctionRow]] = defaultdict(list)
    files: dict[str, list[FunctionRow]] = defaultdict(list)
    for row in rows:
        modules[row.module].append(row)
        files[row.file].append(row)

    module_summary = {name: bucket(items) for name, items in sorted(modules.items())}
    file_summary = {name: bucket(items) for name, items in sorted(files.items())}
    overall = bucket(rows)

    hot_files = []
    for file, items in files.items():
        non_final = [row for row in items if row.non_final]
        hot_files.append({
            "file": file,
            "module": file.split("/", 1)[0] if "/" in file else ".",
            "total": len(items),
            "non_final": len(non_final),
            "mapped_non_final": sum(1 for row in non_final if row.mapped),
            "finalish_percent": bucket(items)["finalish_percent"],
        })
    hot_files.sort(key=lambda item: (-item["non_final"], -item["mapped_non_final"], item["file"]))

    next_candidates = []
    for row in rows:
        if not row.non_final or not row.mapped:
            continue
        caller_count = len([x for x in row.callers.split(";") if x])
        callee_count = len([x for x in row.called_functions.split(";") if x])
        score = row.body_size + caller_count * 80 + callee_count * 20
        next_candidates.append({
            "score": score,
            "address": row.final_psx_address,
            "function": row.repo_function,
            "file": row.file,
            "line": row.line,
            "status": row.status,
            "markers": sorted(row.markers),
            "body_size": row.body_size,
            "callers": caller_count,
            "callees": callee_count,
        })
    next_candidates.sort(key=lambda item: (-item["score"], item["file"], item["line"]))

    return {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "source_rows": len(rows),
        "status_definitions": {
            "unknown": "No final/decompile/debug marker and no useful mapping/name signal.",
            "named": "Mapped/named, but not marked final/decompiled/debugged.",
            "decompiled": "Named repo function without final/debug marker.",
            "final": "Contains `(F)`.",
            "debugged": "Contains `(D)`; stronger than `(F)` for tracking.",
            "binary_matched": "Contains `(**)`.",
        },
        "overall": overall,
        "modules": module_summary,
        "files": file_summary,
        "hot_files": hot_files[:30],
        "next_candidates": next_candidates[:40],
    }


def bullet_count(label: str, data: dict) -> list[str]:
    statuses = data["statuses"]
    return [
        f"- {label}",
        f"  - total: `{data['total']}`",
        f"  - mapped: `{data['mapped']}` (`{data['mapped_percent']}%`)",
        f"  - final/debug/binary-matched: `{data['finalish']}` (`{data['finalish_percent']}%`)",
        f"  - F: `{statuses['final']}`; D: `{statuses['debugged']}`; binary-matched: `{statuses['binary_matched']}`; decompiled: `{statuses['decompiled']}`; named: `{statuses['named']}`; unknown: `{statuses['unknown']}`; ND: `{data['nd']}`",
    ]


def write_markdown(path: Path, summary: dict) -> None:
    lines: list[str] = []
    lines.extend([
        "# TOMB5 reverse progress",
        "",
        f"Generated: `{summary['generated_at']}`",
        "",
        "## Status definitions",
        "",
    ])
    for name in STATUS_ORDER:
        lines.append(f"- `{name}`: {summary['status_definitions'][name]}")
    lines.extend(["", "## Overall", ""])
    lines.extend(bullet_count("Repo functions in mapping", summary["overall"]))

    lines.extend(["", "## Modules", ""])
    for module, data in sorted(summary["modules"].items(), key=lambda item: (-item[1]["total"], item[0])):
        lines.extend(bullet_count(module, data))

    lines.extend(["", "## Files with most non-final functions", ""])
    for item in summary["hot_files"]:
        lines.extend([
            f"- `{item['file']}`",
            f"  - non-final: `{item['non_final']}` / `{item['total']}`",
            f"  - mapped non-final: `{item['mapped_non_final']}`",
            f"  - final/debug/binary-matched: `{item['finalish_percent']}%`",
        ])

    lines.extend(["", "## Next candidates", ""])
    for item in summary["next_candidates"][:20]:
        marker_text = ", ".join(item["markers"]) if item["markers"] else "none"
        lines.extend([
            f"- `{item['address']}` `{item['function']}` — score `{item['score']}`",
            f"  - file: `{item['file']}:{item['line']}`",
            f"  - status: `{item['status']}`; markers: `{marker_text}`",
            f"  - body_size: `{item['body_size']}`; callers: `{item['callers']}`; callees: `{item['callees']}`",
        ])

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", default=".", help="TOMB5 repo root; default: current directory")
    parser.add_argument("--input", default="docs/reverse/generated/repo-function-map.csv", help="mapping CSV relative to repo root")
    parser.add_argument("--json", default="docs/reverse/generated/progress.json", help="output JSON relative to repo root")
    parser.add_argument("--markdown", default="docs/reverse/progress.md", help="output Markdown relative to repo root")
    args = parser.parse_args()

    repo = Path(args.repo).resolve()
    input_path = repo / args.input
    if not input_path.exists():
        raise SystemExit(f"Missing mapping CSV: {input_path}; run scripts/reverse/map_ghidra_to_repo.py first")

    rows = read_rows(input_path)
    if not rows:
        raise SystemExit(f"No rows parsed from {input_path}")
    summary = summarize(rows)

    json_path = repo / args.json
    json_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    write_markdown(repo / args.markdown, summary)

    print(json.dumps({
        "input": str(input_path),
        "json": str(json_path),
        "markdown": str(repo / args.markdown),
        "overall": summary["overall"],
        "module_count": len(summary["modules"]),
        "file_count": len(summary["files"]),
    }, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
